# Generated by Django 4.2.10 on 2024-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration',
            field=models.IntegerField(),
        ),
    ]
