# Generated by Django 4.2.10 on 2024-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_payment_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVV',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
