# Generated by Django 4.2.10 on 2024-03-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_payment_cvv_alter_payment_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVV',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(),
        ),
    ]
